volumes:
  parkpro:

services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      MONGOHOST: mongo
      MONGODATABASE: parkpro
      MONGOUSER: parkpro
      MONGOPASSWORD: parkpro
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - parkpro:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: parkpro
      MONGO_INITDB_ROOT_PASSWORD: parkpro

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: parkpro
      ME_CONFIG_MONGODB_ADMINPASSWORD: parkpro
      ME_CONFIG_MONGODB_URL: mongodb://parkpro:parkpro@mongo:27017/
    depends_on:
      - mongo
